### ISSUE TITLE
config file structure - explanation of ideas and discussion

### ISSUE THREAD

**Issue by RaT0M** [multiply-org/prior-engine#6]
@JorisTimmermans we should agree upon a config file structure. Discussion is now initialized :smiley: 
I don't know about your experience with this, so I just start rambling.

Maybe you saw my sample config already.. to explain my layout ideas:

- `Prior` section:
   Section in global config file reserved for prior stuff
- `priors` subsection:
   all uncommented entries are used/provided to inference engine. this may be toggled on/off by the user.
- e.g. `sm_clim` subsubsection:
    holding information relevant to the specific module/method in prior engine.
    here: type, filepath, ..

``` YAML
Prior:
  priors:
    sm_clim:
      type: climatology
      climatology_file: ../aux_data/CCI_SM_climatology_eur_merged_inv.nc
    # sm_recent:
    #       type: recent
    # sm_static:
    #       type: static
    # sm_dynamic:
    #     type: dynamic
    #     model:
    #         - API
    #         - other

    #? veg_pft:
    #?   type: pft
    #?   database: /aux_data/some_DB
    #? veg_spec:
    #?   type: species
    #?   database: /user_data/some_DB
```
The original list structure from the very-alpha-version of the config file is replaced by a more dictionary centered way. this would in my mind make it easier to access the right values rather than have explicit references to list numbers which should be avoided as @TonioF already was very correct about  (#3).

@TonioF (also José?) could guide me (us?) here with a 'good practice' advice and feasibility assessment..

@McWhity also brought up a nice way to access the dictionary structure:

``` python
class AttributeDict(object):
    """
    A class to convert a nested Dictionary into an object with key-values
    accessibly using attribute notation (AttributeDict.attribute) instead of
    key notation (Dict["key"]). This class recursively sets Dicts to objects,
    allowing you to recurse down nested dicts (like: AttributeDict.attr.attr)
    """
    def __init__(self, **entries):
        self.add_entries(**entries)

    def add_entries(self, **entries):
        for key, value in entries.items():
            if type(value) is dict:
                self.__dict__[key] = AttributeDict(**value)
            else:
                self.__dict__[key] = value

    def __getitem__(self, key):
        """
        Provides dict-style access to attributes
        """
        return getattr(self, key)
```
Then load:
``` python
    def _get_config(self):
        """
        Load configuration from self.config.bb.pre_process()
           writes to self.config.
        """
        with open(self.config, 'r') as cfg:
            self.config = yaml.load(cfg)
            self.config = AttributeDict(**self.config)
```
and access in our case e.g.:
``` python
    self.config.Prior.priors.sm_clim.type
```
(also shorten and reassign subsubsection to single prior specific config (e.g. `SoilmoisturePrior.config`).

Should we use this approach as well? (Could be implemented module independent as well..)

What are your thoughts on this generally? still not *that* important? split the config files?

*PS: would be nice if you could just wink at my lack of experience with config file input to python scripts, if its too obvious, and state the right way.*

**Comment by RaT0M** [comment]
After talking with @JorisTimmermans about the structure of the *config file* we came up with some adjustments.

These are also based on the idea that the `prior-engine` may/should get a **list of variables**, which are asked for in the `inference-engine` by the user,  to provide prior data accordingly. (see #7).

``` yaml
Prior:
  priors:
    soil:
      clim:
        climatology_file: ../aux_data/CCI_SM_climatology_eur_merged_inv.nc
      recent:
        some_input: info
      static:
        some_input: info
      dynamic:
        model:
           - API
           - other
    vegetation:
    #? veg_pft:
    #?   type: pft
    #?   database: /aux_data/some_DB
    #? veg_spec:
    #?   type: species
    #?   database: /user_data/some_DB
```
At time of writing I'm uncertain if the discussed structure was not rather :
```yaml
Prior:
  priors:
    soil:
      climatology_file: ../aux_data/CCI_SM_climatology_eur_merged_inv.nc
      ...
    vegetation:  
      ...
```
(which would eliminate the option to avoid climatological calculations, besides not providing an input file)

Any thoughts @TonioF , @jgomezdans ?

**Comment by TonioF** [comment]
Hi,
to be frank, after I have seen your (@JorisTimmermans and @RaT0M) different takes on the Prior Engine I am not too sure what the structure should look like. I think you should agree on this (in case you didn't already do that). There is not really something you could break when using a YAML file, so if you see that accessing values easier in a certain way, go ahead.
I find it a bit confusing though that the main section is called "Prior" (i.e., a single prior) and the subsection "priors" (multiple priors). Would "Prior_Engine" be a better name for the section? Also, I thought we would use exactly one prior to run the MULTIPLY workflow. Am I missing something here?  

The AttributeDict is nice. It looks like something we should add to the central code archive of utility methods we do not have yet. Also, it looks like something that can be tested very well ;) . 

Regarding the last post: If the old structure is too restrictive, change it. It is definitely a good approach to keep the platform as generic as possible.

**Comment by RaT0M** [comment]
Right now the _config_ structure has settled on:
``` yaml
General:
....
Inference:
...
Prior:
# Prior section conventions

# - 1. sub-level contains all potential variables (sm, roughness, lai, ..)
#   which are asked for/being inferred from Orchestrator/Inferrence Engine
#   and for which prior information is provided.
# - 2. sub-level contains prior type (ptype). These can be commented out
#   to be omitted. 

  General:
    # directory for Joris' prior files (in General section because used for more variables):
    directory_data: ../aux_data/Static/Vegetation/
  sm:
    climatology:
      climatology_dir: ../aux_data/Climatology/SoilMoisture/
    # dynamic:
    #     type: dynamic
    #     model:
    #         - API
    #         - other
    # recent:
    #   aux_data = ...
    # static:
    #       type: static
  lai:
    database: 
  cab:
    database:
    #climatology:
    #  database: ../aux_data/new_geotiff
    # model:

```
